### ISSUE TITLE
Хранить секреты в коде - не лучшая идея

### ISSUE THREAD

**Issue by StephanYorchenko** [1Shadowscale1/pddurfubot#1]
https://github.com/1Shadowscale1/pddurfubot/blob/554f2cbeaf57a9895e070d9cb19fdb44ffc94511/src/main/java/pddurfubot/Bot.java#L49

**Comment by Sallo0** [comment]
В процессе исправления

**Comment by 1Shadowscale1** [comment]
Исправлено
